"""
Manuscript number ledger — the single wiring point between the stats scripts
and the LaTeX manuscript.

Every headline quantity the manuscript quotes is ``record()``-ed by the stats
script that computes it, at the point of computation. The ledger accumulates
in ``paper/latex/numbers.json`` and renders to ``paper/latex/numbers.tex`` as
``\\nepi<Key>`` macros, which ``main.tex`` and ``extended_data.tex`` use in
place of typed literals. Whole table bodies are written as
``paper/latex/tab_<name>.tex`` fragments and ``\\input`` by the manuscript.

Regenerating the numbers is therefore the same action as regenerating the
results: run the stats scripts, then recompile the manuscript. A hand-typed
number in the manuscript is a bug.

Policy: the ledger covers model outputs (ratios, intervals, elasticities,
shares, sample sizes). Definitional constants (distance bands, trip rate) and
deliberately approximate prose ("about 2,500 miles") stay in the text.
"""

from __future__ import annotations

import json
import re

from urban_energy.paths import PROJECT_DIR

LATEX_DIR = PROJECT_DIR / "paper" / "latex"
_JSON = LATEX_DIR / "numbers.json"
_TEX = LATEX_DIR / "numbers.tex"

_KEY = re.compile(r"[a-zA-Z]+")

_HEADER = (
    "% Generated by the stats scripts via stats/ledger.py — do not edit.\n"
    "% Regenerate by running the stats scripts (see paper/submission_checklist.md).\n"
)

# Rounded prose variants derived from recorded keys at render time, so the
# approximate forms ("about 27 times", "a 2.1x gap") stay wired to the same
# source as the precise ones. {derived key: (source key, decimals)}.
_DERIVED: dict[str, tuple[str, int]] = {
    "walkAmenRound": ("walkAmen", 0),
    "driveAmenRound": ("driveAmen", 0),
    "totalGapRound": ("totalGap", 1),
}


def record(**kv: str | float | int) -> None:
    """Record named manuscript numbers and re-render ``numbers.tex``.

    Keys must be alphabetic (they become LaTeX macro names ``\\nepi<Key>``).
    Values are stored as strings exactly as they should appear in prose.
    """
    data = json.loads(_JSON.read_text()) if _JSON.exists() else {}
    for key, value in kv.items():
        if not _KEY.fullmatch(key):
            raise ValueError(f"ledger key must be alphabetic: {key!r}")
        data[key] = str(value)
    LATEX_DIR.mkdir(parents=True, exist_ok=True)
    _JSON.write_text(json.dumps(data, indent=1, sort_keys=True))
    rendered = dict(data)
    for derived, (source, nd) in _DERIVED.items():
        if source in rendered:
            rendered[derived] = f"{float(rendered[source]):.{nd}f}"
    tex = _HEADER + "".join(
        f"\\newcommand{{\\nepi{k}}}{{{v}}}\n" for k, v in sorted(rendered.items())
    )
    _TEX.write_text(tex)


#: Rendered table specifications. Each output ``tab_<file>.tex`` is a COMPLETE
#: tabular (TeX cannot ``\input`` rows inside an alignment), assembled from one
#: or more recorded parts so multi-script tables stay single-sourced.
_TABLES: dict[str, dict[str, object]] = {
    "axesaccess": {
        "cols": "lrrrrrr",
        "header": " & Flat & Terraced & \\shortstack[r]{Semi-\\\\detached} & "
        "Detached & \\shortstack[r]{Dominant-\\\\type median} & "
        "\\shortstack[r]{Pure-type\\\\ratio} \\\\",
        "parts": ["axesaccess"],
    },
    "axesenergy": {
        "cols": "lrrrrrrr",
        "header": " & Flat & Terraced & \\shortstack[r]{Semi-\\\\detached} & "
        "Detached & \\shortstack[r]{Dominant-\\\\type median} & "
        "\\shortstack[r]{Pure-type\\\\ratio} & "
        "\\shortstack[r]{Equal\\\\household size} \\\\",
        "parts": ["axesenergy"],
    },
    "scenarios": {
        "cols": "lcc",
        "header": "Scenario & Unadjusted [95\\% CI] & "
        "Equal household size [95\\% CI] \\\\",
        "parts": ["scenarios"],
    },
    "oster": {
        "cols": "lccccc",
        "header": "Outcome & Raw & + confounds & + NS-SeC & Oster $\\delta^{*}$ & "
        "Adjusted at $\\delta = 1$ \\\\",
        "parts": ["oster"],
    },
    "maup": {
        "cols": "lrcccc",
        "header": "Scale & Units & Home [95\\% CI] & Total [95\\% CI] & "
        "Home (medians) & Total (medians) \\\\",
        "parts": ["maup"],
    },
    "publictransport": {
        "cols": "lcc",
        "header": "Public-transport energy & Travel Det:Flat [95\\% CI] & "
        "Total Det:Flat [95\\% CI] \\\\",
        "parts": ["publictransport"],
    },
}

_PARTS = LATEX_DIR / "tables.json"


def table(name: str, body: str) -> None:
    """Record a table part and re-render every complete ``tab_*.tex`` file.

    ``body`` is complete rows (``\\\\`` line ends). Parts are stored in
    ``tables.json``; each spec in ``_TABLES`` composes its parts into a full
    tabular environment, written as ``tab_<spec>.tex`` once all parts exist.
    """
    if not _KEY.fullmatch(name):
        raise ValueError(f"table name must be alphabetic: {name!r}")
    LATEX_DIR.mkdir(parents=True, exist_ok=True)
    parts = json.loads(_PARTS.read_text()) if _PARTS.exists() else {}
    parts[name] = body
    _PARTS.write_text(json.dumps(parts, indent=1, sort_keys=True))
    for out, spec in _TABLES.items():
        if not all(p in parts for p in spec["parts"]):
            continue
        rows = "\\midrule\n".join(parts[p] for p in spec["parts"])
        tex = (
            _HEADER
            + f"\\begin{{tabular}}{{{spec['cols']}}}\n\\toprule\n{spec['header']}\n"
            + f"\\midrule\n{rows}\\botrule\n\\end{{tabular}}\n"
        )
        (LATEX_DIR / f"tab_{out}.tex").write_text(tex)


def value(key: str, default: str = "") -> str:
    """Read a recorded value back from the ledger (for figures that display
    quantities computed elsewhere, e.g. the rate's cluster-bootstrap CI)."""
    if not _JSON.exists():
        return default
    return json.loads(_JSON.read_text()).get(key, default)


def pt(x: float, nd: int = 2) -> str:
    """Format a point estimate to ``nd`` decimals."""
    return f"{x:.{nd}f}"


def ci(lo: float, hi: float, nd: int = 2) -> str:
    """Format an interval as ``lo--hi`` to ``nd`` decimals."""
    return f"{lo:.{nd}f}--{hi:.{nd}f}"
